upstream_images:
  - upstream_image: "tensorflow/tensorflow:2.17.0-gpu"
    destination: "tensorflow-2.17.0-gpu"
  - upstream_image: "pytorch/pytorch:2.4.1-cuda11.8-cudnn9-devel"
    destination: "pytorch-2.4.1-cuda11.8-cudnn9-devel"
  - upstream_image: "nvidia/cuda:12.5.1-cudnn-devel-ubuntu20.04"
    destination: "nvidia-cuda-12.5.1-cudnn-devel-ubuntu20.04"
  - upstream_image: "neo4j:enterprise"
    destination: "neo4j-enterprise"
  - upstream_image: "elasticsearch:8.15.0"
    destination: "elasticsearch-8.15.0"
  - upstream_image: "spark:python3-java17"
    destination: "spark-python3-java17"
  - upstream_image: "storm:2.6"
    destination: "storm-2.6"
  - upstream_image: "flink:1.20-java8"
    destination: "flink-1.20-java8"
  - upstream_image: "bitnami/airflow-worker:2.10.1"
    destination: "bitnami-airflow-worker-2.10.1"
  - upstream_image: "mathworks/matlab:r2024a"
    destination: "mathworks-matlab-r2024a"
  #- upstream_image: "google/deepvariant:deepsomatic-v17_rc0_07012024-gpu"
  #  destination: "google-deepvariant-deepsomatic-v17_rc0_07012024-gpu"
  - upstream_image: "google/cloud-sdk:491.0.0"
    destination: "google-cloud-sdk-491.0.0"
  - upstream_image: "google/deepsomatic:1.7.0-gpu"
    destination: "google-deepsomatic-1.7.0-gpu"
  - upstream_image: "ollama/ollama:0.3.10"
    destination: "ollama-0.3.10"
