version: "3"

vars:
  IMAGES: [ 'python:3.11', 'nvidia/cuda:12.5.1-cudnn-devel-ubuntu20.04', 'tensorflow/tensorflow:2.17.0-gpu' ]

tasks:
  test:
    interactive: true
    vars:
      image: 'nvidia/cuda:12.5.1-cudnn-devel-ubuntu20.04'
    cmds:
      - rm -rf oci/{{.image | replace ":" "/" }}/image_new/
      - cargo run --profile=lto -- oci/{{.image | replace ":" "/" }}/ repack --target-size=500MB --exclude='*.pyc' {{.CLI_ARGS}}
      - skopeo copy --override-arch=arm64 --override-os=linux oci:oci/{{.image | replace ":" "/" }}/image_new/ docker-daemon:foo:abc

  run-and-export:
    requires:
      vars: [ image ]
    vars:
      compression_level: 19
      image_path: 'oci/{{.image | replace ":" "/" }}'
      image_slug: '{{.image | replace ":" "-" | replace "/" "-" }}'
      tmp_dir:
        sh: mktemp -d
    interactive: true
    cmds:
      - rm -rf oci/{{.image | replace ":" "/" }}/image_new/
      - cargo run --profile=lto -- oci/{{.image | replace ":" "/" }}/ repack --target-size=300MB --compression-level={{.compression_level}}
      - skopeo copy --override-arch=arm64 --override-os=linux oci:{{.image_path }}/image_new/ docker://orfal/split:repacked-{{.image_slug}}
      - cargo run --profile=lto -- oci/{{.image | replace ":" "/" }}/ repack --target-size=300MB --compression-level={{.compression_level}} --split-files=100MB
      - skopeo copy --override-arch=arm64 --override-os=linux oci:{{.image_path }}/image_new/ docker://orfal/split:split-{{.image_slug}}
      - skopeo copy --override-arch=arm64 --override-os=linux oci:{{.image_path }}/image/ docker://orfal/split:original-{{.image_slug}}
  #      - skopeo copy --override-arch=arm64 --override-os=linux oci:{{.image_path }}/image/ dir://{{.tmp_dir}} --dest-compress --dest-compress-format=zstd --dest-compress-level={{.compression_level}}
  #      - skopeo copy --override-arch=arm64 --override-os=linux dir://{{.tmp_dir}}  docker://orfal/split:zstd-{{.image_slug}}

  test-all:
    cmds:
      - for: { var: IMAGES }
        task: run-and-export
        vars:
          image: '{{.ITEM}}'
