name: 'Repack Image Benchmark'
description: 'Repack an image for benchmarking'
inputs:
  upstream-image:
    required: true
  target-size:
    required: true
  source:
    required: false
    default: 'oci://original/'
  output:
    required: false
    default: 'repacked'
  image-push-prefix:
    required: true
outputs:
  image-reference-ghcr:
    description: "pushed image reference - ghcr"
    value: ${{ steps.push.outputs.image-reference-ghcr }}
  image-reference-dockerhub:
    description: "pushed image reference - dockerhub"
    value: ${{ steps.push.outputs.image-reference-dockerhub }}
runs:
  using: "composite"
  steps:
    - name: Repack
      id: repack
      run: |
        ./docker-repack "oci://${{ inputs.source }}" ${{ env.OUTPUT_DIR }} --target-size="${{ inputs.target-size }}"
        echo "output-dir=${{ env.OUTPUT_DIR }}" >> $GITHUB_OUTPUT
      shell: bash
      env:
        OUTPUT_DIR: "${{ inputs.output }}/${{ inputs.target-size }}/"

    - id: push
      uses: ./.github/actions/push-image
      with:
        upstream-image: '${{ inputs.upstream-image }}'
        oci-directory: '${{ steps.repack.outputs.output-dir }}'

    - name: Cleanup
      run: rm -rf "${{ steps.repack.outputs.output-dir }}"
      shell: bash
