name: 'Push image'
description: 'Push an image to Dockerhub and GHCR'
inputs:
  source:
    required: true
  upstream-image:
    required: true
  tag-suffix:
    required: true

outputs:
  image-reference-ghcr:
    description: "pushed image reference for ghcr"
    value: ${{ steps.push-ghcr.outputs.image-reference }}
  image-reference-dockerhub:
    description: "pushed image reference for dockerhub"
    value: ${{ steps.push-dockerhub.outputs.image-reference }}
runs:
  using: "composite"
  steps:
    - name: Compute tag
      id: compute-tag
      run: |
        TAG="$(echo "${{ inputs.upstream-image }}" | tr '/' '-' | tr ':' '-')-${{ inputs.tag-suffix }}"
        echo "Computed tag: ${TAG}:"
        echo "Upstream image: ${{ inputs.upstream-image }}"
        echo "Suffix: ${{ inputs.tag-suffix }}"
        echo "tag=${TAG}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Push image - ghcr.io
      id: push-ghcr
      run: |
        skopeo copy --all --image-parallel-copies=10 oci:${{ inputs.source }} "docker://${{ env.IMAGE_REFERENCE }}"
        echo "image-reference=${{ env.IMAGE_REFERENCE }}" >> $GITHUB_OUTPUT
      shell: bash
      env:
        IMAGE_REFERENCE: "ghcr.io/${{ github.repository }}/docker-repack-demo:${{ steps.compute-tag.outputs.tag }}"

    - name: Push image - docker.io
      id: push-dockerhub
      run: |
        skopeo copy --all --image-parallel-copies=10 oci:${{ inputs.source }} "docker://${{ env.IMAGE_REFERENCE }}"
        echo "image-reference=${{ env.IMAGE_REFERENCE }}" >> $GITHUB_OUTPUT
      shell: bash
      env:
        IMAGE_REFERENCE: "docker.io/orfal/docker-repack-demo:${{ steps.compute-tag.outputs.tag }}"
