name: containerd

on:
  push:

jobs:
  pull-image:
#    strategy:
#      fail-fast: false
#      matrix:
#        image:
#          - orfal/split:zstd-python-3.11
#          - orfal/split:original-python-3.11
#          - orfal/split:repacked-python-3.11
    runs-on: ubuntu-latest
    steps:
      - name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v3
      - name: install hyperfine
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: sharkdp/hyperfine
          cache: enable
      - name: install nerdctl
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: containerd/nerdctl
          cache: enable

      - name: benchmark
        run: sudo env "PATH=$PATH" hyperfine --runs 5
              --parameter-list image ${{ images }} 
              'nerdctl image pull --all-platforms {image} --unpack=false' 
              --cleanup 'nerdctl image rm docker.io/{image}'
        with:
          images: |
            ${{ join([
              'docker.io/orfal/split:zstd-python-3.11',
              'docker.io/orfal/split:original-python-3.11',
            ], ',') }}


  #      - name: unpack
#        run: nerdctl image pull --all-platforms docker.io/${{ matrix.image }} --unpack=false
#      - name: Pull Docker image
#        run: sudo ctr i pull --max-concurrent-downloads=50 docker.io/${{ matrix.image }} &2> /dev/null

  diagram:
    permissions:
      actions: read
    runs-on: ubuntu-latest
    needs: [ pull-image ]
    steps:
      - uses: Kesin11/actions-timeline@v2
        with:
          show-waiting-runner: 'false'