name: Benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  time-pull:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      id-token: write

    env:
      RUNS: 50

    steps:
      - uses: actions/checkout@v4
      - name: install skopeo
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: lework/skopeo-binary
          tag: v1.16.1
          cache: true
          extension-matching: disable
          rename-to: skopeo
          chmod: 0755

      - name: skopeo version
        run: skopeo --version

      - name: "Skopeo authenticate ghcr.io"
        run: skopeo login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - run: wget -q https://github.com/sharkdp/hyperfine/releases/download/v1.16.1/hyperfine_1.16.1_amd64.deb
      - run: sudo dpkg -i hyperfine_1.16.1_amd64.deb
      - run: hyperfine --version

      - name: Output matrix
        id: matrix
        run: |
          echo "images=$(cat benchmark/sources.json | jq -rc '[.upstream_images[] | sub(":"; "-") | sub("/"; "-")] | join(",")')" >> "$GITHUB_OUTPUT"

      - name: Run Benchmark
        run: >-
          hyperfine "skopeo copy --image-parallel-copies=10 docker://${{ env.tag_prefix }}:{image}-{suffix} oci:/dev/shm/image" \
            --warmup 5 \
            -L suffix ${{ env.tags }} \
            -L image ${{ steps.matrix.outputs.images }} \
            --prepare "rm -rf /dev/shm/image/" \
            --cleanup "rm -rf /dev/shm/image/" \
            --runs="${{ env.RUNS }}" --export-json=results.json --shell=none
        env:
          tag_prefix: "ghcr.io/${{ github.repository }}/docker-repack-demo"
          tags: original,zstd,25MB,50MB,100MB,200MB
#          tags: original,zstd,25MB,50MB,100MB,200MB,500MB

      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: results.json
          retention-days: 1
          if-no-files-found: error
