name: containerd

on:
  push:

jobs:
  containerd:
    strategy:
      fail-fast: false
      matrix:
        image:
          - orfal/split:zstd-python-3.11
          - orfal/split:original-python-3.11
          - orfal/split:repacked-python-3.11
    runs-on: ubuntu-latest
    steps:
      - name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v3

      - name: Pull Docker image
        run: sudo ctr i pull --max-concurrent-downloads=50 docker.io/${{ matrix.image }} &2> /dev/null

  diagram:
    permissions:
      actions: read
    runs-on: ubuntu-latest
    needs: [ containerd ]
    steps:
      - uses: Kesin11/actions-timeline@v2
        with:
          show-waiting-runner: 'false'