name: Benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-matrix:
    runs-on: ubuntu-latest

    outputs:
      upstream_images: ${{ steps.matrix.outputs.upstream_images }}

    steps:
      - uses: actions/checkout@v4

      - name: Output matrix
        id: matrix
        run: |
          echo "upstream_images=$(cat benchmark/sources.json | jq -rc '.upstream_images')" >> "$GITHUB_OUTPUT"

  time-pull:
    runs-on: ubuntu-latest
    needs: build-matrix

    permissions:
      contents: read
      packages: read
      id-token: write

    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        upstream_image: ${{ fromJSON(needs.build-matrix.outputs.upstream_images) }}
        #tag: [ 'original', 'repacked-25MB', 'repacked-50MB', 'repacked-100MB', 'repacked-200MB' ]

    env:
      RUNS: 20

    steps:
      - name: install skopeo
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: lework/skopeo-binary
          tag: v1.16.1
          cache: true
          extension-matching: disable
          rename-to: skopeo
          chmod: 0755

      - name: skopeo version
        run: skopeo --version

      - name: "Skopeo authenticate ghcr.io"
        run: skopeo login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - run: wget -q https://github.com/sharkdp/hyperfine/releases/download/v1.16.1/hyperfine_1.16.1_amd64.deb
      - run: sudo dpkg -i hyperfine_1.16.1_amd64.deb
      - run: hyperfine --version

      - id: tag
        run: |
          TAG="$(echo "${{ matrix.upstream_image }}" | tr '/' '-' | tr ':' '-')"
          echo "Tag: ${TAG}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Run Benchmark
        run: >-
          hyperfine "skopeo copy --image-parallel-copies=10 docker://${{ env.tag_prefix }}-{suffix} oci:/dev/shm/image" \
            -L suffix ${{ env.tags }} \
            --prepare "rm -rf /dev/shm/image/" \
            --runs="${{ env.RUNS }}" --export-json=results.json --shell=none
        env:
          tag_prefix: ghcr.io/${{ github.repository }}/docker-repack-demo:${{ steps.tag.outputs.tag }}
          tags: original,zstd,25MB,50MB,100MB,200MB

      - uses: actions/upload-artifact@v4
        with:
          name: results-${{ steps.tag.outputs.tag }}
          path: results.json
          retention-days: 1
          if-no-files-found: error
