name: containerd

on:
  push:

jobs:
  pull-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'containers/skopeo'

      - uses: actions/setup-go@v5
        with:
          cache: 'true'
          go-version: '^1.22.0'

      - name: install hyperfine
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: sharkdp/hyperfine
          # https://github.com/jaxxstorm/action-install-gh-release/issues/88
          tag: v1.18.0
          binaries-location: hyperfine-v1.18.0-x86_64-unknown-linux-gnu
          cache: true

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libgpgme-dev libassuan-dev libbtrfs-dev pkg-config
          version: 1

      - name: Cache skopeo
        id: cache-skopeo
        uses: actions/cache@v4
        with:
          path: bin/skopeo
          key: ${{ runner.os }}-skopeo

      - run: DISABLE_DOCS=1 make bin/skopeo
        if: steps.cache-primes.outputs.cache-hit != 'true'

      - run: ./bin/skopeo --version
      - run: ./bin/skopeo copy docker://docker.io/orfal/split:zstd-python-3.11 oci-archive:test
      - run: ./bin/skopeo copy docker://docker.io/orfal/split:zstd-python-3.11 oci-archive:test

#      - name: benchmark
#        run: sudo env "PATH=$PATH" hyperfine --runs 5
#              --show-output
#              --parameter-list image "${images}"
#              './bin/skopeo copy --quiet --image-parallel-copies=10 --all docker://{image} oci-archive:test'
#              --cleanup 'nerdctl image rm {image}'
#        env:
#          images: >-
#            docker.io/orfal/split:zstd-python-3.11,
#            docker.io/orfal/split:original-python-3.11

  diagram:
    permissions:
      actions: read
    runs-on: ubuntu-latest
    needs: [ pull-image ]
    steps:
      - uses: Kesin11/actions-timeline@v2
        with:
          show-waiting-runner: 'false'