name: Cleanup images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Delete all containers from package without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
          token: ${{ github.token }}
          #repository_owner: ${{ github.repository_owner }}
          #repository: ${{ github.repository }}
          #package_name: the-package-name
          untagged_only: true
          owner_type: user
