name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  actions: read
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: web/package-lock.json

      - run: npm install
        working-directory: web/

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - run: npm run build
        working-directory: web/
        env:
          SITE_HOST: ${{ steps.pages.outputs.origin }}
          SITE_PREFIX: ${{ steps.pages.outputs.base_path }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'web/dist/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
