name: Repack image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}/demo
  TARGET_SIZE: "100MB"
  TARGET_IMAGE: "nvidia/cuda:12.5.1-cudnn-devel-ubuntu20.04"

concurrency:
  group: "repack"
  cancel-in-progress: true

jobs:
  repack-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Disk space before
        run: df -h
      - name: Maximize build space
        shell: bash
        run: |
          sudo rm -rf /usr/share/dotnet &
          sudo rm -rf /usr/local/lib/android &
          sudo rm -rf /opt/ghc &
          sudo rm -rf /opt/hostedtoolcache/CodeQL &
          sudo docker image prune --all --force > /dev/null &
          wait
      - name: Disk space after
        run: df -h
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-on-failure: 'false'

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.5

      - name: Build
        run: cargo install --profile=lto --path=. --locked
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
          RUSTFLAGS: '-C target-cpu=native'

      - name: install skopeo
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: lework/skopeo-binary
          tag: v1.16.1
          cache: enable
          extension-matching: "disable"

      - name: Cache Image
        id: cache-image
        uses: actions/cache@v4
        with:
          path: image/
          key: nvidia-cuda-image

#      - name: Download image
#        if: steps.cache-image.outputs.cache-hit != 'true'
#        run: skopeo copy docker://nvidia/cuda:12.5.1-cudnn-devel-ubuntu20.04 oci:image

      - name: Repack image
        run: docker-repack docker://nvidia/cuda:12.5.1-cudnn-devel-ubuntu20.04 repacked/ --target-size=${{ env.TARGET_SIZE }}

      - name: "Skopeo authenticate"
        run: skopeo login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}

      - name: Copy original gzip
        run: skopeo copy docker://${{ env.TARGET_IMAGE }} "docker://${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ env.TARGET_IMAGE }}-original"

      - name: Copy repacked
        run: skopeo copy oci:repacked/ "docker://${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ env.TARGET_IMAGE }}-repacked"

#      - name: Copy original zstd
#        run: skopeo copy oci:image/ "docker://${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ env.TARGET_IMAGE }}-zstd"

