name: Repack image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-on-failure: 'false'

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.5

      - name: Build
        run: cargo build --profile=release
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"

      - uses: actions/upload-artifact@v4
        with:
          name: cli
          path: target/release/docker-repack*
          retention-days: 1

  repack-image:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        target_image: [
          "nvidia/cuda:12.5.1-cudnn-devel-ubuntu20.04",
          "tensorflow/tensorflow:2.17.0-gpu",
          "neo4j:enterprise",
          "elasticsearch:8.15.0",
          "python:3.12",
        ]
        type: ["50MB", "100MB", "200MB"]

    concurrency:
      group: "push-${{ matrix.target_image }}-${{ matrix.type }}"
      cancel-in-progress: false

    env:
      REGISTRY: ghcr.io
      IMAGE_PREFIX: ${{ github.repository }}/demo

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cli

      - run: chmod +x docker-repack
      - run: ./docker-repack --version

      - name: Disk space before
        run: df -h

      - name: Maximize build space
        shell: bash
        run: |
          sudo rm -rf /usr/share/dotnet/* &
          sudo rm -rf /usr/local/lib/android/* &
          wait
      - name: Disk space after
        run: df -h

      - name: install skopeo
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: lework/skopeo-binary
          tag: v1.16.1
          cache: disable
          extension-matching: disable
          rename-to: skopeo
          chmod: 0755

      - name: skopeo version
        run: skopeo --version

      - name: "Skopeo authenticate"
        run: skopeo login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}

      - name: "Docker authenticate"
        run: docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}

      - name: Copy original
        run: skopeo copy --all --image-parallel-copies=10 docker://${{ matrix.target_image }} "docker://${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.target_image }}-original"

      - name: Repack image
        run: ./docker-repack docker://${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.target_image }}-original repacked/ --target-size=${{ matrix.type }}

      - name: Copy repacked
        run: skopeo copy --all --image-parallel-copies=10 oci:repacked/ "docker://${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.target_image }}-repacked-${{ matrix.type }}"
